# Generated by Django 3.0.3 on 2020-04-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug_field',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
